### ISSUE TITLE
Course code cannot be shared - Please make this repository private 

### ISSUE THREAD

**Issue by Sumukh** [kfei/cs61a#1]
I wanted to let you know that this repository is publicly accessible which means some unscrupulous students could easily copy your code - and you would be held responsible as well. You should make this repo private ASAP.

GitHub allows you to get free private repository with this link - https://education.github.com

From the 61A course polices for partner projects: 
Do not share your code with anyone but your partner, and do not read anyone but your partner's code. **Write your own programs and keep them to yourself.**

**Comment by kfei** [comment]
Unfortunately I'm not a student. I just join this course for self learning.
So I can not get the free private repo (which asks me to provide a student ID).
But I'll consider pushing my code after the hw/proj/quiz's deadline.

Thanks for your suggestion.

**Comment by Sumukh** [comment]
https://bitbucket.org offers free private repos to anyone.
Could you use that instead?
